[tool.poetry]
name = "layers"
version = "0.1.0"
description = ""
authors = []
packages = [
    { include = "nrlf", from = "." },
]

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
