---
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: .pre-commit-config.yaml

  - repo: https://github.com/prettier/pre-commit
    rev: 57f39166b5a5a504d6808b87ab98d41ebf095b46
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        name: Prevent commits to dev / master
        entry: no-commit-to-branch
        language: python
        args: [-b, develop, -b, master, -b, main]
        pass_filenames: false

  # Remove unused imports
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.2
    hooks:
      - id: autoflake
        args:
          - "--check-diff"

  # Flake8 for print only (error code T201)
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-print
        args:
          - "--select=T201"
          - "--exclude=.git,__pycache__,dist,.venv,scripts,packages/feature_documentation/*"

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black, --filter-files]

  - repo: https://github.com/ducminh-phan/reformat-gherkin
    rev: v3.0.1
    hooks:
      - id: reformat-gherkin

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-write=true
          - --args=-recursive
