repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: .pre-commit-config.yaml

  - repo: https://github.com/prettier/pre-commit
    rev: 57f39166b5a5a504d6808b87ab98d41ebf095b46
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        name: Prevent commits to dev / master
        entry: no-commit-to-branch
        language: python
        args: [-b, develop, -b, master, -b, main]
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
