[tool.poetry]
name = "nrlf-api"
version = "1.0.0"
description = ""
authors = ["NHS Digital"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aws-lambda-powertools = "^2.9.0"
nhs-number = "==1.2.1"
pydantic = "==1.10.2"
nrlf-lambda-pipeline = {git = "https://github.com/NHSDigital/nrlf-lambda-pipeline.git", tag = "v0.4.0"}
pytest = "^7.2.0"
boto3 = "^1.26.22"
pyjwt = "^2.6.0"
cryptography = "^38.0.4"
more-itertools = "^9.0.0"
typing-extensions = "^4.5.0"
flake8-print = "^5.0.0"
requests = "^2.28.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
sh = "^1.14.3"
awscli = "^1.27.3"
moto = "^4.0.9"
behave = "^1.2.6"
datamodel-code-generator = "^0.13.5"
pyyaml = "^5.4"
pre-commit = "^2.20.0"
flake8 = "^5.0.4"
black = "^22.10.0"
pyhcl = "^0.4.4"
requests = "^2.28.1"
boto3 = "^1.26.3"
build-scripts = { path = "./scripts/build_scripts/", develop = true }
nrlf = { path = "./layer/nrlf/", develop = true }
lambda-utils = { path = "./layer/lambda_utils/", develop = true }
helpers = { path = "./helpers/", develop = true }
fire = "^0.5.0"
cookiecutter = "^2.1.1"
gherkin-official = "^24.1.0"
ez-setup = "^0.9"
pygments = "^2.14.0"
atlassian-python-api = "^3.32.2"
hypothesis = "^6.68.2"
flake8-print = "^5.0.0"

[tool.poetry.group.legacy]
optional = true

[tool.poetry.group.legacy.dependencies]
libffx = "0.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
