[tool.poetry]
name = "nrlf-api"
version = "1.0.0"
description = ""
authors = ["NHS Digital"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aws-lambda-powertools = "==1.29.2"
nhs-number = "==1.2.1"
pydantic = "==1.10.2"
nrlf-lambda-pipeline = {git = "https://github.com/NHSDigital/nrlf-lambda-pipeline.git", tag = "v0.2.0"}
libffx = "0.0.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
sh = "^1.14.3"
awscli = "^1.27.3"
moto = "^4.0.9"
behave = "^1.2.6"
datamodel-code-generator = "^0.13.5"
pyyaml = "^5.4"
pre-commit = "^2.20.0"
flake8 = "^5.0.4"
black = "^22.10.0"
pyhcl = "^0.4.4"
requests = "^2.28.1"
boto3 = "^1.26.3"
build-scripts = { path = "./scripts/build_scripts/", develop = true }
nrlf = { path = "./layer/nrlf/", develop = true }
lambda-utils = { path = "./layer/lambda_utils/", develop = true }

[tool.poetry.group.sandbox]
optional = true

[tool.poetry.group.sandbox.dependencies]
terraform-local = "^0.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
