openapi: 3.0.0
info:
  title: NRLF Consumer API
  version: 0.0.1
servers:
  - url: /
tags:
  - name: NRLF Consumer
paths:
  /DocumentReference:
    get:
      tags:
        - NRLF Consumer
      summary: Search for DocumentReference resources
      operationId: searchDocumentReference
      parameters:
        - $ref: "#/components/parameters/subject"
        - $ref: "#/components/parameters/custodian"
        - $ref: "#/components/parameters/snomedCode"
        - $ref: "#/components/parameters/fromASID"
        - $ref: "#/components/parameters/toASID"
      responses:
        "200":
          description: Search DocumentReference operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/Bundle"
            application/fhir+xml:
              schema:
                $ref: "#/components/schemas/Bundle"
      security:
        - ${authoriser_name}: []
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${method_searchDocumentReference}
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
  /DocumentReference/_search:
    post:
      tags:
        - NRLF Consumer
      summary: Search for DocumentReference resources
      operationId: searchPostDocumentReference
      parameters:
        - $ref: "#/components/parameters/fromASID"
        - $ref: "#/components/parameters/toASID"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestParams"
      responses:
        "200":
          description: Search DocumentReference operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/Bundle"
      security:
        - ${authoriser_name}: []
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${method_searchPostDocumentReference}
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
  /DocumentReference/{id}:
    get:
      tags:
        - NRLF Consumer
      summary: Read a DocumentReference resource
      operationId: readDocumentReference
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: Read DocumentReference operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/DocumentReference"
      security:
        - ${authoriser_name}: []
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${method_readDocumentReference}
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
