name: "Runner setup"
description: "Setup runner required packages for project. Python, Pipenv and set required vars"
runs:
  using: "composite"
  steps:
    #    - name: Set up Python 3.9
    #      uses: actions/setup-python@v4
    #      with:
    #        python-version: 3.9.15
    #
    #    - name: Install poetry
    #      run: pip install poetry
    #      shell: bash
    #
    #    - name: Set up terraform 1.0.0
    #      uses: hashicorp/setup-terraform@v2
    #      with:
    #        terraform_version: 1.0.0
    #        terraform_wrapper: false

    - name: Set short sha env var
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      shell: bash
