name: "Set Environment ID"
description: "Set the ID of the environment based on the branch name and pull request"
inputs:
  branch-name:
    description: "The name of the branch"
    required: true

  pull-request-id:
    description: "The ID of the pull request"
    default: "0"

outputs:
  environment-id:
    description: "The ID of the environment"
    value: ${{ steps.set-environment-id.outputs.environment-id }}

runs:
  using: "composite"
  steps:
    - name: Extract Jira Ticket
      id: extract-jira
      runs: |
        JIRA_TICKET=$(
          echo '${{ inputs.branch-name }}' | \
          grep -Po --color=none '[A-z]{3,4}-[0-9]{3,5}' | \
          sed 's/-//g' | \
          tr '[:upper:]' '[:lower:]' || \
          true
        )
        echo "jira-ticket=${JIRA_TICKET}" > $GITHUB_OUTPUT

    - name: Generate Branch Hash
      id: generate-hash
      run: |
        BRANCH_HASH=$(echo '${{ inputs.branch-name }}${{ inputs.pull-request-id }}' | sha256sum | head -c 6)
        echo "branch-hash=${BRANCH_HASH}" > $GITHUB_OUTPUT

    - name: Set Environment ID
      id: set-environment-id
      run: |
        if [ -z "$JIRA_TICKET" ]; then
          echo "environment-id=${BRANCH_HASH}" > $GITHUB_OUTPUT
        else
          echo "environment-id=${JIRA_TICKET}-${BRANCH_HASH}" > $GITHUB_OUTPUT
        fi
      env:
        JIRA_TICKET: ${{ steps.extract-jira.outputs.jira-ticket }}
        BRANCH_HASH: ${{ steps.generate-hash.outputs.branch-hash }}
