name: "Setup Caches"
inputs:
  create-asdf-cache:
    description: "Cache the asdf installation and tools"
    default: true

  create-poetry-cache:
    description: "Cache poetry and dependencies"
    default: true

runs:
  using: "composite"
  steps:
    - name: Setup asdf cache
      if: ${{ inputs.create-asdf-cache }}
      uses: actions/cache@v4
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-asdf-

    - name: Setup poetry cache
      if: ${{ inputs.create-poetry-cache }}
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
