name: "Setup AWS Credentials"

inputs:
  aws-account-name:
    description: "The target AWS account to setup credentials for. Default to the management account."
    default: null
  role-name:
    description: "The role to assume within the target account"
    default: "terraform"
  skip-mgmt:
    description: "Skip setting up credentials for the management account"
    default: false

runs:
  using: "composite"
  steps:
    - name: Configure Management Account Credentials
      if: ${{ inputs.skip-mgmt == false }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: ${{ secrets.CI_ROLE_NAME }}
        role-session-name: github-actions-ci-run${{ github.run_number }}-attempt${{ github.run_attempt }}
        mask-aws-account-id: true
        unset-current-credentials: true

    - name: Get Target Account ID
      id: get-account-id
      if: ${{ inputs.aws_account_name != null }}
      run: |
        TARGET_ACCOUNT_ID=$(aws secretsmanager get-secret-value --secret-id nhsd-nrlf--mgmt--${{ inputs.aws-account-name }}-account-id --query SecretString --output text)
        echo "::add-mask::${TARGET_ACCOUNT_ID}"
        echo "target-account-id=${TARGET_ACCOUNT_ID}" >> $GITHUB_OUTPUT

    - name: Configure Target Account Credentials
      if: ${{ inputs.aws_account_name != null }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-chaining: true
        aws-region: eu-west-2
        role-session-name: github-actions-ci-run${{ github.run_number }}-attempt${{ github.run_attempt }}
        role-to-assume: arn:aws:iam::${{ steps.get-account-id.outputs.target-account-id }}:role/${{ inputs.role-name }}
        aws-account-id: ${{ steps.get-account-id.outputs.target-account-id }}
