name: "Upload artifact"
description: "Upload artifact"
inputs:
  name:
    description: "Name of artifact. Will be prefixed with GITHUB_SHA_SHORT"
    required: true
  path:
    description: "Path of files to upload"
    required: true
  retention-days:
    description: "Number of days to retain artifact"
    required: false
    default: "1"
runs:
  using: "composite"
  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.GITHUB_SHA_SHORT }}-${{ inputs.name }}
        path: ${{ inputs.path }}
        retention-days: ${{ inputs.retention-days }}
