openapi: 3.0.0
info:
  title: DocumentReference API
  version: 4.0.1
servers:
  - url: /fhir-server/api/v4
tags:
  - name: DocumentReference
paths:
  /DocumentReference:
    get:
      tags:
        - DocumentReference
      summary: Search for DocumentReference resources
      operationId: searchDocumentReference
      parameters:
        - $ref: "#/components/parameters/subject"
        - $ref: "#/components/parameters/custodian"
        - $ref: "#/components/parameters/snomedCode"
        - $ref: "#/components/parameters/fromASID"
        - $ref: "#/components/parameters/toASID"
      responses:
        "200":
          description: Search DocumentReference operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/Bundle"
            application/fhir+xml:
              schema:
                $ref: "#/components/schemas/Bundle"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${method_searchDocumentReference}
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
    post:
      tags:
        - DocumentReference
      summary: Create a DocumentReference resource
      operationId: createDocumentReference
      parameters:
        - $ref: "#/components/parameters/fromASID"
        - $ref: "#/components/parameters/toASID"
      responses:
        "201":
          $ref: "#/components/responses/Success"
      requestBody:
        $ref: "#/components/requestBodies/DocumentReference"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${method_createDocumentReference}
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
  /DocumentReference/{id}:
    get:
      tags:
        - DocumentReference
      summary: Read a DocumentReference resource
      operationId: readDocumentReference
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: Read DocumentReference operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/DocumentReference"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${method_readDocumentReference}
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
    put:
      tags:
        - DocumentReference
      summary: Update an existing DocumentReference resource
      operationId: updateDocumentReference
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/fromASID"
        - $ref: "#/components/parameters/toASID"
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "201":
          $ref: "#/components/responses/Success"
      requestBody:
        $ref: "#/components/requestBodies/DocumentReference"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${method_updateDocumentReference}
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
    delete:
      tags:
        - DocumentReference
      summary: Delete a DocumentReference resource
      operationId: deleteDocumentReference
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/fromASID"
        - $ref: "#/components/parameters/toASID"
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "204":
          $ref: "#/components/responses/Success"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${method_deleteDocumentReference}
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
