name: CI

on: pull_request

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  set-uniquish-id:
    # Set a uniquish ID - good enough for our purposes since it must be close enough to unique for
    # a) Terraform / AWS to allow clean build/destroys without side-effects (e.g. we don't
    #    want resources marked for deletion to be recreated in another CI run)
    # b) Not to fall foul of character limits on AWS resource names: the ID must be short
    name: Set a uniquish ID
    runs-on: [self-hosted, ci]
    steps:
      - name: Set a uniquish ID
        id: set_uniqish_id
        run: |
          TIME_IN_SECONDS_SINCE_MIDNIGHT=$(date -d "1970-01-01 UTC $(date +%T)" +%s)
          echo "uniqish_id=${GITHUB_SHA::7}-${TIME_IN_SECONDS_SINCE_MIDNIGHT}" >> $GITHUB_OUTPUT
    outputs:
      uniqish_id: ${{ steps.set_uniqish_id.outputs.uniqish_id }}

  lint-check:
    name: Linting check (head)
    runs-on: [self-hosted, ci]
    steps:
      - name: Git Clone - ${{ github.event.pull_request.base.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
