name: Clear Cache

on: workflow_dispatch

permissions:
  contents: read
  actions: write

jobs:
  clear-cache:
    name: Clear Cache
    runs-on: ubuntu-latest

    steps:
      - name: Clear all cache
        uses: actions/github-script@v6
        with:
          script: |
            console.log("About to clear")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              console.log("Clearing cache")
              console.log(cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Clear completed")
