name: Merge to main

on:
  push:
    branches:
      - feature/NRLF-455-slack-integration

permissions: write-all

env:
  TF_WORKFLOW_ID: ${{ inputs.environment }}
  ENVIRONMENT: ${{ inputs.environment }}
  CACHE_NAME: ${{ inputs.environment }}-cache
  ARTIFACT_NAME: ${{ inputs.environment }}-artifact
  TF_ARTIFACT_NAME: ${{ inputs.environment }}-terraform-artifact
  AWS_DEFAULT_REGION: eu-west-2
  TF_CLI_ARGS: -no-color
  RUNNING_IN_CI: 1
  CI_DEPLOY_PERSISTENT_ENV: 1

jobs:
  extract-branch:
    name: Get reference branch
    runs-on: [self-hosted, ci]
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch

  make_tag:
    runs-on: ubuntu-latest
    needs: [extract-branch]
    name: Create a tag from main
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Extract the tag name from the RELEASE file
        run: |
          TAG=${{ steps.extract_branch.outputs.branch }}
          echo "tag=${TAG}" >> $GITHUB_ENV
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.tag }}',
              sha: context.sha
            })
    outputs:
      tag: ${{ env.tag }}

  # comment
  message-slack:
    name: Notify slack of merge to main
    needs: [make_tag]
    runs-on: [self-hosted, ci]
    steps:
      - name: Send merge result to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "branch": "${{ steps.extract_branch.outputs.branch }}"
              "tag": "${{ needs.make_tag.tag}}""
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MAIN_MERGE_SLACK_HOOK_URL }}
