name: Deploy PR Environment
run-name: "${{ github.event.action == 'synchronize' && 'Update' || 'Create' }} PR Environment - #${{ github.event.pull_request.number }} (${{ github.event.pull_request.title }})"

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: environment-${{ github.event.pull_request.number }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  actions: write
  issues: write
  pull-requests: write

jobs:
  set-environment-id:
    name: Set Environment ID
    runs-on: [self-hosted, ci]
    outputs:
      environment_id: ${{ steps.set-environment-id.outputs.environment-id }}
    steps:
      - name: Set Environment ID
        id: set-environment-id
        uses: ./.github/actions/set-environment-id
        with:
          branch-name: ${{ github.event.pull_request.head.ref }}
          pull-request-id: ${{ github.event.pull_request.number }}

  build:
    name: Build Application
    runs-on: [self-hosted, ci]
    needs: [set-environment-id]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Cache
        uses: ./.github/actions/setup-cache

      - name: Install Tools
        uses: ./.github/actions/install-tools

      - name: Run Linting
        run: make lint

      - name: Run Unit Tests
        run: make test

      - name: Build Project
        run: make build

      - name: Save Build Artifacts
        uses: ./.github/actions/upload-artifact
        with:
          name: build-artifacts
          path: dist/*.zip
          environment: ${{ needs.set-environment-id.outputs.environment_id }}
          sensitive: false

      - name: Add Failure Pull Request Comment
        uses: actions/github-script@v7
        if: ${{ failure() }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `💥 Something went wrong while building the pull request environment.\n[Check Output Logs](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
            })

  deploy:
    name: Deploy PR Environment
    runs-on: [self-hosted, ci]
    needs: [set-environment-id, build]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Tools
        uses: ./.github/actions/install-tools

      - name: Setup Management Credentials
        uses: .github/actions/setup-credentials

      - name: Download Build Artifacts
        uses: .github/actions/download-artifact
        with:
          name: build-artifacts
          path: dist
          environment: ${{ needs.set-environment-id.outputs.environment_id }}

      - name: Retrieve Server Certificates
        run: aws s3 cp s3://nhsd-nrlf--truststore/server/dev.pem truststore/server/dev.pem

      - name: Get AWS Account ID
        id: get_account_id
        run: echo "aws_account_id=$(aws secretsmanager get-secret-value --secret-id nhsd-nrlf--mgmt--dev-account-id --query SecretString --output text)" >> "$GITHUB_OUTPUT"

      - name: Terraform Init
        run: |
          terraform -chdir=terraform/infrastructure init
          terraform -chdir=terraform/infrastructure workspace new ${{ needs.set-environment-id.outputs.environment_id }} || \
          terraform -chdir=terraform/infrastructure workspace select ${{ needs.set-environment-id.outputs.environment_id }}

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform/infrastructure plan \
            --var-file=etc/dev.tfvars \
            --var assume_account=${{ steps.get_account_id.outputs.aws_account_id }} \
            --var assume_role=terraform \
            -out tfplan

      - name: Terraform Apply
        id: terraform-apply
        run: |
          terraform -chdir=terraform/infrastructure apply tfplan

      - name: Add Success Pull Request Comment
        uses: actions/github-script@v7
        if: ${{ success() }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🚀 PR environment successfully deployed.\nCommit Hash: `${{ github.event.pull_request.head.sha }}`\nURL: https://${{ needs.set-environment-id.outputs.environment_id }}.api.record-locator.dev.national.nhs.uk/"
            })

      - name: Add Failure Pull Request Comment
        uses: actions/github-script@v7
        if: ${{ failure() }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `💥 Something went wrong while deploying the pull request environment.\n[Check Output Logs](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
            })

  integration-test:
    name: Run Integration Tests
    needs: [set-environment-id, deploy]
    runs-on: [self-hosted, ci]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Tools
        uses: .github/actions/install-tools

      - name: Configure Management Credentials
        uses: .github/actions/setup-credentials

      - name: Retrieve Client Certificates
        run: make truststore-pull-client ENV=dev

      - name: Configure Dev Account Credentials
        uses: .github/actions/setup-credentials
        with:
          aws-account-name: dev
          skip-mgmt: true

      - name: Run Integration Tests
        run: make test-features-integration TF_WORKSPACE=${{ needs.set-environment-id.outputs.environment_id }}

  performance-test:
    name: Run Performance Tests
    needs: [set-environment-id, integration-test]
    runs-on: [self-hosted, ci]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Tools
        uses: .github/actions/install-tools

      - name: Configure Management Credentials
        uses: ./.github/actions/setup-credentials

      - name: Pull Client Certificates
        run: make truststore-pull-client ENV=dev

      - name: Configure Dev Account Credentials
        uses: ./.github/actions/setup-credentials
        with:
          aws-account-name: dev
          skip-mgmt: true

      - name: Setup Environment Test Data
        run: make test-performance-prepare TF_WORKSPACE=${{ needs.set-environment-id.outputs.environment_id }}

      - name: Run Performance Test - Baseline
        run: make test-performance-baseline HOST=${{ needs.set-environment-id.outputs.environment_id }}.api.record-locator.dev.national.nhs.uk ENV_TYPE=dev

      - name: Run Performance Test - Stress
        run: make test-performance-stress HOST=${{ needs.set-environment-id.outputs.environment_id }}.api.record-locator.dev.national.nhs.uk ENV_TYPE=dev

      - name: Process Performance Test Outputs
        run: make test-performance-output

      - name: Store Performance Test Outputs
        uses: ./.github/actions/upload-artifact
        with:
          name: performance-test
          path: dist/*.png
          environment: ${{ needs.set-environment-id.outputs.environment_id }}

      - name: Cleanup Environment Test Data
        run: make test-performance-cleanup TF_WORKSPACE=${{ needs.set-environment-id.outputs.environment_id }}
